feat: genesis migration docs and scripts
fetchai/genesis-fetchhub pull request #1
Opened 2021-07-05 12:17 UTC by daeMOn63

2021-07-05 17:30 UTC, pbukva requested changes
see my in-line comment.

2021-07-05 17:30 UTC, pbukva commented on scripts/staking/collect_staked.js
> +            console.log(`${key},${user.pubkey},${secp256k1UncompressedPubkeyToFetchAddress(user.pubkey)},${principal.add(compound).toFixed()},${principal.toFixed()},${compound.toFixed()}`);
I would suggest 2 things here - well, ultiatelly the place to implement them woul be in the `constructor(...)` method of `User` class:
1. relocate derivation of fetch address (= `secp256k1UncompressedPubkeyToFetchAddress(...)` call) in to `User.contructor(...)` and store the address as data member of `User` class
2. Insie `User.contructor(...)` add verification of derived public key by deriving Ethereum address out of it and **comparing** it against `User.address` data-member - these2 value must be equal. If they are not, something is not right - please `assert` that in the constructor.
This assumes that this check is not done already  in the `getPublicKeyFromTxHash(...)` function.

2021-07-06 08:54 UTC, daeMOn63 commented on scripts/staking/collect_staked.js
> +            console.log(`${key},${user.pubkey},${secp256k1UncompressedPubkeyToFetchAddress(user.pubkey)},${principal.add(compound).toFixed()},${principal.toFixed()},${compound.toFixed()}`);
Thanks, added, and regenerated the sample export - all pubkeys / address pairs verified properly

2021-09-13 13:36 UTC, ejfitzgerald commented on README.md
> +2) Stop the network at around 14:00 UTC (height: 2436700)
Does this need to be updated now?

2021-09-13 13:36 UTC, ejfitzgerald commented on README.md
> +2) Stop the network at around 14:00 UTC (height: 2436700)
Ignore my stupid comment

2021-09-14 13:25 UTC, merged